---
title: "Practice 3"
subtitle: 'BIOL 4994/4991'
author: "Ariana Negroni Santiago"
date: "Last compiled on `r format(Sys.time(), '%Y-%b-%d, %I:%M %p')`"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---

```{r warning=FALSE, message=FALSE, echo=FALSE}
#install.packages("knitr")
#install.packages("gaawr2")
#install.packages("kableExtra")
#install.packages("gt")
library(gaawr2)
library(dplyr)
library(kableExtra)
library(knitr)
library(gt)
data(diabetes)
head(diabetes)
```


```{r}
kable(head(diabetes,5), booktabs = TRUE) %>% 
  kable_styling(font_size=12)
```


```{r}
kable(head(diabetes,5), booktabs = TRUE) %>% 
  kable_styling(font_size = 12) %>% 
  kable_styling(bootstrap_options = "striped", full_width=F)
```


Para señalar solo las columnas deseadas:
```{r}
kable(head(diabetes[2:4],5), booktabs = TRUE) %>% 
  kable_styling(font_size = 12) %>% 
  kable_styling(bootstrap_options = "striped", full_width=F)
```

Changing position
```{r}
kable(head(diabetes[,4:5]), booktabs = TRUE) %>% 
  kable_styling(font_size = 12, position = "left") %>% 
  kable_styling(bootstrap_options = "striped", full_width=F)
```

Adding headers
```{r}
kable(head(diabetes, 5), booktabs = TRUE) %>% 
  kable_styling(font_size = 12, position = "left") %>% 
  kable_styling(bootstrap_options = "striped", full_width=F) %>% 
  add_header_above(c("Personal data" = 4, "Blood Profile"=10))
```

```{r}
kable(diabetes, digits=2,format = "html", row.names = TRUE) %>% 
  kable_styling(bootstrap_options = c("striped"), full_width = T, font_size = 15) %>% 
  scroll_box(height = "300px")
```


Nuevo paquete
```{r}
diabetes %>% 
  dplyr::select(ID, No_Pation, Gender, AGE) %>% 
  gt_preview()
```

